BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Documents" (
	"Id"	INTEGER NOT NULL DEFAULT 1000 UNIQUE,
	"FileName"	VARCHAR NOT NULL,
	"FileType"	VARCHAR NOT NULL,
	"Base64"	BINARY NOT NULL,
	"Student_ID"	VARCHAR NOT NULL,
	FOREIGN KEY("Student_ID") REFERENCES "Students"("Student_ID"),
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "ScanTime" (
	"Id"	INTEGER NOT NULL DEFAULT 1000 UNIQUE,
	"Time"	INTEGER NOT NULL,
	"Student_ID"	VARCHAR(14) NOT NULL,
	FOREIGN KEY("Student_ID") REFERENCES "Students"("Student_ID"),
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Students" (
	"Student_ID"	VARCHAR NOT NULL UNIQUE,
	"Name"	VARCHAR NOT NULL,
	"Photo"	BINARY,
	"rfid_tag"	INTEGER UNIQUE,
	PRIMARY KEY("Student_ID")
);
INSERT INTO "Students" ("Student_ID","Name","Photo","rfid_tag") VALUES ('116210905041-6','อภิสิทธิ์ น้อยหลวงชัย',NULL,1),
 ('116210905030-9','ภาสวัฒน์ นรมั่น',NULL,2),
 ('116210905030-99','ภาสวัฒน์ นรมั่น',NULL,3);
COMMIT;
